/**
 * Reminders_Feed_v1.4.0.gs — OPTIONAL, ONE-TIME, MANUAL migration, plus the
 * read-only feed it unlocks.
 *
 * Do not run the migration automatically. Run it yourself from the Apps
 * Script editor (runRemindersFeedV140Migration) once, before pointing an
 * Apple Shortcut at this workbook.
 *
 * BACKGROUND: Apps Script has no API into Apple Reminders — there is no way
 * for this workbook to write a reminder onto your phone directly. The
 * realistic bridge is: this workbook exposes a small, token-protected JSON
 * feed of not-yet-synced Assignments; an Apple Shortcut (built once, on your
 * device, in the Shortcuts app — see the setup notes below) fetches that
 * feed, calls "Add New Reminder" for each item, then calls back to mark
 * each one synced so nothing is ever added twice.
 *
 * WHAT THIS ADDS:
 *  1. One new, purely additive checkbox column on "08 Assignments":
 *     "Synced to Reminders" — defaults FALSE for every existing row.
 *  2. One new 02 Settings row: "Reminders sync token" — a random value
 *     (Utilities.getUuid()) generated once, the ONLY thing standing between
 *     this feed and anyone who has the URL (see SECURITY below). Never
 *     regenerated by re-running this migration.
 *  3. doGet(e) in API.gs now checks for feed/markSynced query params BEFORE
 *     serving the normal app page — see the branch added there. Everything
 *     else about how the app loads is unchanged.
 *
 * ENDPOINTS (both require ?token=<your Reminders sync token>):
 *   GET {your web app URL}?feed=assignments&token=...
 *     -> {ok:true, items:[{id,title,module,dueDate}, ...]} for every
 *        Assignment not marked "Synced to Reminders" and not
 *        Submitted/Graded.
 *   GET {your web app URL}?markSynced=<Assignment ID>&token=...
 *     -> {ok:true} — sets that one Assignment's "Synced to Reminders" to
 *        TRUE so the next feed fetch won't return it again.
 *
 * SECURITY — read this before wiring up a Shortcut: for an iOS Shortcut to
 * reach this feed at all, your Apps Script web app deployment must allow
 * "Anyone with the link" (your current appsscript.json is "Only myself",
 * which silently rejects any request without your own logged-in Google
 * session — a Shortcut cannot supply that). Once you allow "Anyone", the
 * token is the ONLY thing gating the feed. This project already trusts
 * exactly this "unlisted long URL" model elsewhere (an ICS Calendar
 * subscription link works the same way) — but treat both the deployment
 * URL and the token like a password: never post either one publicly. For
 * extra isolation, consider making a SEPARATE deployment (Apps Script:
 * Deploy > Manage deployments > New deployment) just for the Shortcut, so
 * your everyday "Only myself" app URL never changes.
 *
 * SHORTCUT SETUP (build this once in the Shortcuts app):
 *   1. "Get Contents of URL" — URL = your feed URL above (GET).
 *   2. "Get Dictionary from Input" -> "Get Value for 'items'" (from the
 *      result of step 1).
 *   3. "Repeat with Each" over that list:
 *        a. "Add New Reminder" — Title = Item's "title", Notes = Item's
 *           "module" + due date, List = whichever Reminders list you want
 *           the widget to show, Due Date = Item's "dueDate".
 *        b. "Get Contents of URL" — URL = your markSynced URL, with
 *           Item's "id" appended, e.g.
 *           {your web app URL}?markSynced=[Item id]&token=...
 *   4. Save the Shortcut, then either run it manually whenever you like,
 *      or add a Personal Automation (e.g. "Time of Day", once each
 *      morning) so it runs itself.
 *
 * Idempotent: safe to run this migration more than once — it never
 * regenerates an existing token or re-adds an existing column.
 */
function runRemindersFeedV140Migration() {
  var report = [];

  var assignSheet = SpreadsheetApp.getActive().getSheetByName(ASSIGNMENTS_SHEET);
  if (!assignSheet) {
    report.push('"' + ASSIGNMENTS_SHEET + '" sheet not found — skipped the "Synced to Reminders" column.');
  } else {
    var col = ensureColumn_(assignSheet, HEADER_ROW, "Synced to Reminders");
    report.push(col.added ? 'Added column: "Synced to Reminders" (defaults FALSE).' : 'Already present: "Synced to Reminders".');
    if (col.added) ensureCheckboxColumn_(assignSheet, HEADER_ROW, "Synced to Reminders");
  }

  var settingsSheet = SpreadsheetApp.getActive().getSheetByName(SETTINGS_SHEET);
  if (!settingsSheet) {
    report.push('"' + SETTINGS_SHEET + '" sheet not found — skipped the Reminders sync token.');
  } else {
    var addedToken = ensureSettingRow_(settingsSheet, "Reminders sync token", Utilities.getUuid());
    report.push(addedToken
      ? 'Added new Settings row: "Reminders sync token" (a random value was generated — open 02 Settings to copy it into your Shortcut).'
      : '"Reminders sync token" already exists in 02 Settings — left exactly as set (not regenerated).');
  }

  report.push('');
  report.push('Read the doc comment at the top of this file (Apps Script editor) for the endpoint URLs, the security trade-off of enabling "Anyone with the link" access, and the Shortcut build steps.');
  report.push('Safe to run again at any time.');
  migrationReport_('Reminders Feed v1.4.0 migration', report);
}

/** Read-only convenience: shows the current Reminders sync token and the
 *  query-string pattern to build your Shortcut's two URLs from (never the
 *  full URL -- that depends on which deployment you point the Shortcut at,
 *  see the SECURITY section in this file's doc comment). Safe to run any
 *  time; changes nothing. */
function showRemindersFeedInfo() {
  var token = getSetting_("Reminders sync token");
  var lines = token
    ? [
      'Reminders sync token: ' + token,
      '',
      'Feed URL:        {your web app URL}?feed=assignments&token=' + token,
      'Mark-synced URL: {your web app URL}?markSynced=<Assignment ID>&token=' + token,
      '',
      'Find "{your web app URL}" under Deploy > Manage deployments in the Apps Script editor. See Reminders_Feed_v1.4.0_Migration.gs\'s doc comment for the full Shortcut build steps and the "Anyone with the link" access trade-off.'
    ]
    : ['"Reminders sync token" not found in 02 Settings -- run runRemindersFeedV140Migration() first.'];
  migrationReport_('Reminders Feed info', lines);
}

/**
 * Dispatches a doGet(e) request that carries feed/markSynced query params —
 * called from doGet in API.gs BEFORE it falls through to serving the normal
 * app page. Always returns JSON, and always requires a matching
 * "Reminders sync token" (see SECURITY in this file's doc comment above);
 * an invalid/missing token gets the same {ok:false} shape as any other
 * failure, never a hint about why it's wrong.
 */
function remindersFeedRequest_(params) {
  var expectedToken = getSetting_("Reminders sync token");
  var result;
  if (!expectedToken || params.token !== expectedToken) {
    result = { ok: false, error: "Invalid or missing token." };
  } else if (params.markSynced) {
    result = remindersMarkSynced_(params.markSynced);
  } else {
    result = remindersFeedJson_();
  }
  return ContentService.createTextOutput(JSON.stringify(result)).setMimeType(ContentService.MimeType.JSON);
}

/** Every Assignment not yet marked "Synced to Reminders" and not already
 *  Submitted/Graded (nothing left to remind about once it's in). Read-only. */
function remindersFeedJson_() {
  try {
    var sheet = SpreadsheetApp.getActive().getSheetByName(ASSIGNMENTS_SHEET);
    if (!sheet) return { ok: false, error: "Sheet not found: " + ASSIGNMENTS_SHEET };
    var map = getColMap_(sheet);
    if (!map["Synced to Reminders"]) return { ok: false, error: '"Synced to Reminders" column not found — run Reminders_Feed_v1.4.0_Migration.gs first.' };
    var lastRow = sheet.getLastRow();
    var items = [];
    for (var row = HEADER_ROW + 1; row <= lastRow; row++) {
      var id = sheet.getRange(row, col_(map, "Assignment ID")).getValue();
      if (!id) continue;
      if (sheet.getRange(row, col_(map, "Synced to Reminders")).getValue() === true) continue;
      var status = map["Status"] ? sheet.getRange(row, col_(map, "Status")).getValue() : "";
      if (status === "Submitted" || status === "Graded") continue;
      var dueDateVal = map["Due date"] ? sheet.getRange(row, col_(map, "Due date")).getValue() : null;
      items.push({
        id: id,
        title: sheet.getRange(row, col_(map, "Title")).getValue(),
        module: map["Module"] ? sheet.getRange(row, col_(map, "Module")).getValue() : "",
        dueDate: (dueDateVal instanceof Date) ? Utilities.formatDate(dueDateVal, TIMEZONE, "yyyy-MM-dd") : ""
      });
    }
    return { ok: true, items: items };
  } catch (e) { return { ok: false, error: e && e.message ? e.message : String(e) }; }
}

/** Marks one Assignment synced so the next feed fetch won't return it again. */
function remindersMarkSynced_(assignmentId) {
  var lock = LockService.getScriptLock();
  try {
    if (!lock.tryLock(LOCK_WAIT_MS)) return { ok: false, error: "Workbook is busy — try again shortly." };
    var sheet = SpreadsheetApp.getActive().getSheetByName(ASSIGNMENTS_SHEET);
    if (!sheet) return { ok: false, error: "Sheet not found: " + ASSIGNMENTS_SHEET };
    var map = getColMap_(sheet);
    if (!map["Synced to Reminders"]) return { ok: false, error: '"Synced to Reminders" column not found.' };
    var row = findRowByStableId_(ASSIGNMENTS_SHEET, "Assignment ID", assignmentId);
    if (row === -1) return { ok: false, error: "Assignment not found: " + assignmentId };
    sheet.getRange(row, col_(map, "Synced to Reminders")).setValue(true);
    logAutomation_("Assignment marked synced to Reminders", String(assignmentId), "Updated", "");
    return { ok: true };
  } catch (e) { return { ok: false, error: e && e.message ? e.message : String(e) }; } finally { lock.releaseLock(); }
}
